name: Slither Analysis

on:
  push:
    branches:
      - foundry
  pull_request:
    branches:
      - main

jobs:
  slither-analysis:
    name: Slither Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

#      - name: Install Foundry
#        uses: foundry-rs/foundry-toolchain@v1
#        with:
#          version: nightly

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install dependencies
        run: yarn install

      - name: Initialize hardhat
        run: npx hardhat compile

      - name: Test with Slither
        #run: yarn run test:slither
        run: slither .
        working-directory: ./contracts